# Generated by Django 2.0 on 2018-10-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='EmailID',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='Fax',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='PhoneNo',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
